[build]
  publish = "tu-directorio-de-publicacion"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

# Ignora directorios específicos
[build.ignore]
  command = "echo 'Ignorando directorios específicos'"