FROM php:8.0-apache

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    libonig-dev \
    libxml2-dev

# Instalar extensiones PHP
RUN docker-php-ext-install pdo pdo_mysql mbstring

# Limpiar caché de apt para reducir tamaño de imagen
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Habilitar reescritura de Apache
RUN a2enmod rewrite